### ISSUE TITLE
Issue adding to cache

### ISSUE THREAD

**Issue by tuhingupta** [jberkus/pgKubernetesTutorial#1]
Getting following error adding to cache - 

minikube cache add registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8
Error caching and loading images: loading cached images: loading image /Users/<user>/.minikube/cache/images/registry.opensource.zalan.do/acid/spilo-cdp-10_1.4-p8: loading docker image: /tmp/spilo-cdp-10_1.4-p8: Process exited with status 1

first time i tried it i got following error:
$ minikube cache add registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8
Error caching and loading images: caching images: caching image /Users/<user>/.minikube/cache/images/registry.opensource.zalan.do/acid/spilo-cdp-10_1.4-p8: copying image: Error reading blob sha256:c25436e28d9dc6019693a4588edb2c365ed94300f74d39929c11217421ca9b26: Get https://registry.opensource.zalan.do/v2/acid/spilo-cdp-10/blobs/sha256:c25436e28d9dc6019693a4588edb2c365ed94300f74d39929c11217421ca9b26: read tcp 172.19.1.84:51678->54.76.2.228:443: read: operation timed out

**Comment by jberkus** [comment]
Hmm, OS/platform? And you're definitely using minikube 0.28?

**Comment by tuhingupta** [comment]
0.28 gives me following error - $ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0713 22:58:25.217701   51195 start.go:299] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

-----------------------

So was reading that it works with v 0.25. It worked however the cache add command failed. 
Not sure if all this issue if because i am using a my companies mac.

**Comment by tuhingupta** [comment]
something that i noticed was - 
this works with v0.28
$ minikube cache add registry.opensource.zalan.do/acid/spilo-9.6:1.2-p26
9801a7a4aadd:~ onz454$ minikube cache list
registry.opensource.zalan.do/acid/spilo-9.6:1.2-p26

however what you have mentioned in section Cache Container Images fails
$ minikube cache add registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8
Error caching and loading images: loading cached images: loading image /Users//.minikube/cache/images/registry.opensource.zalan.do/acid/spilo-cdp-10_1.4-p8: loading docker image: /tmp/spilo-cdp-10_1.4-p8: Process exited with status 1

**Comment by jberkus** [comment]
The 9.6 version is the wrong image and, more importantly, won't deploy on Kubernetes 1.10.  

And strangely it's working here:

22:30 $ minikube cache add registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8

22:32 $ minikube cache list
registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8

However, I'm finding some bug reports with "cache add" on Windows and Mac.  What platform are you on?

**Comment by tuhingupta** [comment]
I am on Mac v10.13.6

**Comment by jberkus** [comment]
Let me test something:

Try:

`minikube cache add jberkus/spilo-demo`

**Comment by tuhingupta** [comment]
Yes that worked!

`$ minikube cache add jberkus/spilo-demo`

`$ minikube cache list`

`jberkus/spilo-demo`

**Comment by jberkus** [comment]
OK, that's really weird, but I did trace it down to sometimes cache add only working with Docker Hub.

Anyway, that's the same image.

Can you also try this one?

jberkus/simple-patroni

**Comment by tuhingupta** [comment]
yes that worked.

`$ minikube cache add jberkus/simple-patroni`

`$ minikube cache list`

`jberkus/simple-patroni`

`jberkus/spilo-demo`

**Comment by jberkus** [comment]
great, thanks, I'll update the Readme!

(issue reported to Minikube)
